package test.ihmcomposant.app;

import test.ihmcomposant.persistance.DatabaseStub;
import test.ihmcomposant.persistance.DocFile;

/**
 *
 * @author Sébastien FRANCOIS
 */
public class IHMDocFiles extends javax.swing.JPanel {
    IHMDocFilesListModel listModel;
    /**
     * Creates new form IHMDocFiles
     */
    public IHMDocFiles() {
        initComponents();
    }

    public IHMDocFiles(DatabaseStub data) {
        initComponents();
        listModel = new IHMDocFilesListModel(data);
        jList1.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        openJButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "titre rubrique", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 128, 0))); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(502, 23));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(502, 130));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        openJButton.setText("Ouvrir");
        openJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(openJButton, gridBagConstraints);

        addJButton.setText("Ajouter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(addJButton, gridBagConstraints);

        deleteJButton.setText("Supprimer");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(deleteJButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>                        

    private void openJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        openFile();
    }                                           

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        if (evt.getClickCount()==2){
            openFile();
        }
    }                                   

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        int index=this.jList1.getSelectedIndex();
        if (index<0){
            return;
        }
        if (listModel.getSize() > 0){
            listModel.removeElementAt(index);
            if (index<listModel.getSize()){
                this.jList1.setSelectedIndex(index);
            } else {
                this.jList1.setSelectedIndex(listModel.getSize()-1);
            }
        }
    }                                             
    private void openFile(){
        int index=this.jList1.getSelectedIndex();
        DocFile file = (DocFile)listModel.get(index);
        IHMDocFileDetails ihm = new IHMDocFileDetails(null, true, file);
        ihm.pack();
        ihm.setVisible(true);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openJButton;
    // End of variables declaration                   
}
